import { PricingPlan } from '../types';

export const PRICING_PLANS: PricingPlan[] = [
  {
    id: 'free',
    name: 'Free Starter',
    tagline: 'Ideal for single community meetups and testing the platform.',
    monthlyPrice: 0,
    annualPrice: 0,
    eventsAllowed: 1,
    registrationLimit: 100,
    staffSeats: 2,
    whatsappMessages: 0,
    customBranding: false,
    advancedReports: false,
    apiAccess: false,
  },
  {
    id: 'starter',
    name: 'Starter',
    tagline: 'For growing organizers running regular workshops and meetups.',
    monthlyPrice: 999,
    annualPrice: 9990,
    eventsAllowed: 5,
    registrationLimit: 1500,
    staffSeats: 5,
    whatsappMessages: 500,
    customBranding: true,
    advancedReports: false,
    apiAccess: false,
  },
  {
    id: 'growth',
    name: 'Growth',
    tagline: 'For professional conferences, business summits, and large expos.',
    monthlyPrice: 2499,
    annualPrice: 24990,
    eventsAllowed: 20,
    registrationLimit: 10000,
    staffSeats: 25,
    whatsappMessages: 5000,
    customBranding: true,
    advancedReports: true,
    apiAccess: true,
    popular: true,
  },
  {
    id: 'business',
    name: 'Enterprise / Business',
    tagline: 'Full white-labeling, unlimited events, dedicated support & SLA.',
    monthlyPrice: 6999,
    annualPrice: 69990,
    eventsAllowed: 'Unlimited',
    registrationLimit: 'Unlimited',
    staffSeats: 'Unlimited',
    whatsappMessages: 25000,
    customBranding: true,
    advancedReports: true,
    apiAccess: true,
  },
];
