import { Attendee } from '../types';

export const mockAttendees: Attendee[] = [
  {
    id: 'att-001',
    registrationId: 'EVT26-000123',
    eventId: 'evt-business-summit-2026',
    eventName: 'Business Summit 2026',
    fullName: 'Arun Kumar',
    email: 'arun.kumar@abctechnologies.in',
    phone: '+91 98421 11223',
    company: 'ABC Technologies Pvt Ltd',
    jobTitle: 'Founder & CEO',
    city: 'Madurai',
    ticketType: 'VIP Delegate',
    status: 'checked_in',
    registeredAt: '2026-09-10T10:32:00Z',
    qrToken: 'TOK_EVT26_000123_AK89',
    checkedInAt: '2026-09-15T10:41:32Z',
    checkedInBy: 'Rahul Sundar (Staff 01)',
    checkedInEntrance: 'Entrance A (North Gate / VIP)',
    checkedInDevice: 'Scanner #1 - iPad Pro Gate A',
    customAnswers: {
      f_delegatetype: 'VIP Delegate',
      f_diet: 'South Indian Vegetarian',
    },
    notes: 'Keynote panelist for 11:30 AM startup session',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'att-002',
    registrationId: 'EVT26-000124',
    eventId: 'evt-business-summit-2026',
    eventName: 'Business Summit 2026',
    fullName: 'Priya Raj',
    email: 'priya.raj@chennaiventures.com',
    phone: '+91 98840 22334',
    company: 'Chennai Angel Ventures',
    jobTitle: 'Managing Partner',
    city: 'Chennai',
    ticketType: 'Investor',
    status: 'checked_in',
    registeredAt: '2026-09-10T11:15:00Z',
    qrToken: 'TOK_EVT26_000124_PR42',
    checkedInAt: '2026-09-15T10:41:21Z',
    checkedInBy: 'Priya Mani (Staff 02)',
    checkedInEntrance: 'Entrance B (Main Hall General)',
    checkedInDevice: 'Scanner #2 - Galaxy Tab Gate B',
    customAnswers: {
      f_delegatetype: 'Investor',
      f_diet: 'Non-Vegetarian',
    },
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'att-003',
    registrationId: 'EVT26-000125',
    eventId: 'evt-business-summit-2026',
    eventName: 'Business Summit 2026',
    fullName: 'Karthik Subramanian',
    email: 'karthik@maduraifinserve.in',
    phone: '+91 94432 99881',
    company: 'Madurai Finserve Logistics',
    jobTitle: 'Chief Technology Officer',
    city: 'Madurai',
    ticketType: 'General Attendee',
    status: 'checked_in',
    registeredAt: '2026-09-11T09:12:00Z',
    qrToken: 'TOK_EVT26_000125_KS55',
    checkedInAt: '2026-09-15T10:40:58Z',
    checkedInBy: 'Rahul Sundar (Staff 01)',
    checkedInEntrance: 'Entrance A (North Gate / VIP)',
    checkedInDevice: 'Scanner #1 - iPad Pro Gate A',
    customAnswers: {
      f_delegatetype: 'General Attendee',
      f_diet: 'South Indian Vegetarian',
    },
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'att-004',
    registrationId: 'EVT26-000126',
    eventId: 'evt-business-summit-2026',
    eventName: 'Business Summit 2026',
    fullName: 'Divya Natarajan',
    email: 'divya@saasmetric.io',
    phone: '+91 97890 33445',
    company: 'SaaSMetric Global',
    jobTitle: 'VP of Product',
    city: 'Bangalore',
    ticketType: 'General Attendee',
    status: 'checked_in',
    registeredAt: '2026-09-11T14:40:00Z',
    qrToken: 'TOK_EVT26_000126_DN19',
    checkedInAt: '2026-09-15T10:39:14Z',
    checkedInBy: 'Karthik Raja (Staff 03)',
    checkedInEntrance: 'Entrance C (East Wing & Media)',
    checkedInDevice: 'Scanner #3 - Pixel 8 Pro Gate C',
    customAnswers: {
      f_delegatetype: 'General Attendee',
      f_diet: 'South Indian Vegetarian',
    },
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'att-005',
    registrationId: 'EVT26-000127',
    eventId: 'evt-business-summit-2026',
    eventName: 'Business Summit 2026',
    fullName: 'Suresh Babu',
    email: 'suresh@kovaitextiles.com',
    phone: '+91 94860 66778',
    company: 'Kovai Smart Textiles',
    jobTitle: 'Executive Director',
    city: 'Coimbatore',
    ticketType: 'VIP Delegate',
    status: 'registered',
    registeredAt: '2026-09-12T08:20:00Z',
    qrToken: 'TOK_EVT26_000127_SB77',
    customAnswers: {
      f_delegatetype: 'VIP Delegate',
      f_diet: 'Non-Vegetarian',
    },
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'att-006',
    registrationId: 'EVT26-000128',
    eventId: 'evt-business-summit-2026',
    eventName: 'Business Summit 2026',
    fullName: 'Ananya Ramesh',
    email: 'ananya@agritechpulse.in',
    phone: '+91 99401 77889',
    company: 'AgriTech Pulse Solutions',
    jobTitle: 'Co-Founder & COO',
    city: 'Trichy',
    ticketType: 'Startup Founder',
    status: 'registered',
    registeredAt: '2026-09-12T16:05:00Z',
    qrToken: 'TOK_EVT26_000128_AR90',
    customAnswers: {
      f_delegatetype: 'Startup Founder',
      f_diet: 'South Indian Vegetarian',
    },
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'att-007',
    registrationId: 'EVT26-000129',
    eventId: 'evt-business-summit-2026',
    eventName: 'Business Summit 2026',
    fullName: 'Venkatesh Raman',
    email: 'venkat@salemmetals.org',
    phone: '+91 94422 11990',
    company: 'Salem Precision Metals',
    jobTitle: 'Managing Partner',
    city: 'Salem',
    ticketType: 'General Attendee',
    status: 'cancelled',
    registeredAt: '2026-09-08T12:00:00Z',
    qrToken: 'TOK_EVT26_000129_VR11',
    customAnswers: {
      f_delegatetype: 'General Attendee',
      f_diet: 'South Indian Vegetarian',
    },
  },
  {
    id: 'att-008',
    registrationId: 'EVT26-000130',
    eventId: 'evt-business-summit-2026',
    eventName: 'Business Summit 2026',
    fullName: 'Meera Krishnan',
    email: 'meera.k@thehindubiz.com',
    phone: '+91 98841 55667',
    company: 'The Hindu Businessline',
    jobTitle: 'Senior Tech Correspondent',
    city: 'Chennai',
    ticketType: 'Media / Press',
    status: 'checked_in',
    registeredAt: '2026-09-13T11:00:00Z',
    qrToken: 'TOK_EVT26_000130_MK34',
    checkedInAt: '2026-09-15T10:35:10Z',
    checkedInBy: 'Karthik Raja (Staff 03)',
    checkedInEntrance: 'Entrance C (East Wing & Media)',
    checkedInDevice: 'Scanner #3 - Pixel 8 Pro Gate C',
    customAnswers: {
      f_delegatetype: 'Media / Press',
      f_diet: 'South Indian Vegetarian',
    },
    avatarUrl: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'att-009',
    registrationId: 'EVT26-000131',
    eventId: 'evt-business-summit-2026',
    eventName: 'Business Summit 2026',
    fullName: 'Deepak Varma',
    email: 'deepak.v@cloudscale.in',
    phone: '+91 96551 88990',
    company: 'CloudScale Networks',
    jobTitle: 'Lead Cloud Architect',
    city: 'Madurai',
    ticketType: 'General Attendee',
    status: 'registered',
    registeredAt: '2026-09-13T15:20:00Z',
    qrToken: 'TOK_EVT26_000131_DV88',
    customAnswers: {
      f_delegatetype: 'General Attendee',
      f_diet: 'Jain Meal',
    },
  },
  {
    id: 'att-010',
    registrationId: 'EVT26-000132',
    eventId: 'evt-business-summit-2026',
    eventName: 'Business Summit 2026',
    fullName: 'Lakshmi Narayanan',
    email: 'lakshmi@maduraipack.com',
    phone: '+91 94431 22445',
    company: 'Pandian Packaging Ltd',
    jobTitle: 'General Manager',
    city: 'Madurai',
    ticketType: 'General Attendee',
    status: 'walk_in',
    registeredAt: '2026-09-15T09:45:00Z',
    qrToken: 'TOK_EVT26_000132_LN62',
    checkedInAt: '2026-09-15T09:45:30Z',
    checkedInBy: 'Rahul Sundar (Staff 01)',
    checkedInEntrance: 'Entrance A (North Gate / VIP)',
    checkedInDevice: 'Scanner #1 - iPad Pro Gate A',
    customAnswers: {
      f_delegatetype: 'General Attendee',
      f_diet: 'South Indian Vegetarian',
    },
  },
  // Additional batch for rich data table & search
  {
    id: 'att-011',
    registrationId: 'EVT26-000133',
    eventId: 'evt-business-summit-2026',
    eventName: 'Business Summit 2026',
    fullName: 'Bala Chandran',
    email: 'bala@sriannaimills.in',
    phone: '+91 98430 44556',
    company: 'Sri Annai Spinning Mills',
    jobTitle: 'Managing Partner',
    city: 'Erode',
    ticketType: 'VIP Delegate',
    status: 'checked_in',
    registeredAt: '2026-09-09T14:10:00Z',
    qrToken: 'TOK_EVT26_000133_BC12',
    checkedInAt: '2026-09-15T10:30:12Z',
    checkedInBy: 'Rahul Sundar (Staff 01)',
    checkedInEntrance: 'Entrance A (North Gate / VIP)',
    checkedInDevice: 'Scanner #1 - iPad Pro Gate A',
  },
  {
    id: 'att-012',
    registrationId: 'EVT26-000134',
    eventId: 'evt-business-summit-2026',
    eventName: 'Business Summit 2026',
    fullName: 'Swetha Parthiban',
    email: 'swetha@fintechsouth.co',
    phone: '+91 97910 88221',
    company: 'Fintech South Hub',
    jobTitle: 'Head of Growth',
    city: 'Chennai',
    ticketType: 'General Attendee',
    status: 'registered',
    registeredAt: '2026-09-14T11:45:00Z',
    qrToken: 'TOK_EVT26_000134_SP99',
  },
  {
    id: 'att-013',
    registrationId: 'EVT26-000135',
    eventId: 'evt-business-summit-2026',
    eventName: 'Business Summit 2026',
    fullName: 'Ganesh Moorthy',
    email: 'ganesh@solarzen.in',
    phone: '+91 94870 12890',
    company: 'SolarZen CleanTech',
    jobTitle: 'Director of Projects',
    city: 'Madurai',
    ticketType: 'Startup Founder',
    status: 'checked_in',
    registeredAt: '2026-09-11T16:20:00Z',
    qrToken: 'TOK_EVT26_000135_GM44',
    checkedInAt: '2026-09-15T10:28:44Z',
    checkedInBy: 'Priya Mani (Staff 02)',
    checkedInEntrance: 'Entrance B (Main Hall General)',
    checkedInDevice: 'Scanner #2 - Galaxy Tab Gate B',
  },
  {
    id: 'att-014',
    registrationId: 'EVT26-000136',
    eventId: 'evt-business-summit-2026',
    eventName: 'Business Summit 2026',
    fullName: 'Kavitha Senthil',
    email: 'kavitha@aihealthlab.org',
    phone: '+91 99440 33211',
    company: 'AI Health Lab India',
    jobTitle: 'Research Scientist',
    city: 'Bangalore',
    ticketType: 'VIP Delegate',
    status: 'registered',
    registeredAt: '2026-09-13T10:05:00Z',
    qrToken: 'TOK_EVT26_000136_KS73',
  },
  {
    id: 'att-015',
    registrationId: 'EVT26-000137',
    eventId: 'evt-business-summit-2026',
    eventName: 'Business Summit 2026',
    fullName: 'Rajesh Kannan',
    email: 'rajesh@kannanautomotive.in',
    phone: '+91 98425 66771',
    company: 'Kannan Automotive Parts',
    jobTitle: 'Proprietor',
    city: 'Madurai',
    ticketType: 'General Attendee',
    status: 'checked_in',
    registeredAt: '2026-09-08T18:30:00Z',
    qrToken: 'TOK_EVT26_000137_RK28',
    checkedInAt: '2026-09-15T10:25:05Z',
    checkedInBy: 'Priya Mani (Staff 02)',
    checkedInEntrance: 'Entrance B (Main Hall General)',
    checkedInDevice: 'Scanner #2 - Galaxy Tab Gate B',
  },
  {
    id: 'att-016',
    registrationId: 'EVT26-000138',
    eventId: 'evt-business-summit-2026',
    eventName: 'Business Summit 2026',
    fullName: 'Naveen Kumar',
    email: 'naveen@nextwavemedia.co',
    phone: '+91 97880 44990',
    company: 'NextWave Digital Media',
    jobTitle: 'Creative Director',
    city: 'Chennai',
    ticketType: 'General Attendee',
    status: 'registered',
    registeredAt: '2026-09-14T09:15:00Z',
    qrToken: 'TOK_EVT26_000138_NK55',
  },
  {
    id: 'att-017',
    registrationId: 'EVT26-000139',
    eventId: 'evt-business-summit-2026',
    eventName: 'Business Summit 2026',
    fullName: 'Harish Shankar',
    email: 'harish@tamildatasystems.com',
    phone: '+91 94433 88112',
    company: 'Tamil Data Systems',
    jobTitle: 'VP Engineering',
    city: 'Madurai',
    ticketType: 'General Attendee',
    status: 'checked_in',
    registeredAt: '2026-09-12T13:40:00Z',
    qrToken: 'TOK_EVT26_000139_HS91',
    checkedInAt: '2026-09-15T10:20:19Z',
    checkedInBy: 'Karthik Raja (Staff 03)',
    checkedInEntrance: 'Entrance C (East Wing & Media)',
    checkedInDevice: 'Scanner #3 - Pixel 8 Pro Gate C',
  },
  {
    id: 'att-018',
    registrationId: 'EVT26-000140',
    eventId: 'evt-business-summit-2026',
    eventName: 'Business Summit 2026',
    fullName: 'Aishwarya Saravanan',
    email: 'aishwarya@vaigaipharma.com',
    phone: '+91 98428 55443',
    company: 'Vaigai Biotech & Pharma',
    jobTitle: 'Chief Quality Officer',
    city: 'Madurai',
    ticketType: 'General Attendee',
    status: 'registered',
    registeredAt: '2026-09-13T17:10:00Z',
    qrToken: 'TOK_EVT26_000140_AS66',
  },
  {
    id: 'att-019',
    registrationId: 'EVT26-000141',
    eventId: 'evt-business-summit-2026',
    eventName: 'Business Summit 2026',
    fullName: 'Thirunavukkarasu M.',
    email: 'thiru@pandiantrust.org',
    phone: '+91 94430 77112',
    company: 'Pandian Educational Trust',
    jobTitle: 'Managing Trustee',
    city: 'Madurai',
    ticketType: 'VIP Delegate',
    status: 'checked_in',
    registeredAt: '2026-09-07T11:20:00Z',
    qrToken: 'TOK_EVT26_000141_TM04',
    checkedInAt: '2026-09-15T10:15:45Z',
    checkedInBy: 'Rahul Sundar (Staff 01)',
    checkedInEntrance: 'Entrance A (North Gate / VIP)',
    checkedInDevice: 'Scanner #1 - iPad Pro Gate A',
  },
  {
    id: 'att-020',
    registrationId: 'EVT26-000142',
    eventId: 'evt-business-summit-2026',
    eventName: 'Business Summit 2026',
    fullName: 'Sindhuja Balaji',
    email: 'sindhuja@chennaistartups.in',
    phone: '+91 98845 11993',
    company: 'Chennai Startup Collective',
    jobTitle: 'Ecosystem Evangelist',
    city: 'Chennai',
    ticketType: 'Startup Founder',
    status: 'registered',
    registeredAt: '2026-09-14T15:30:00Z',
    qrToken: 'TOK_EVT26_000142_SB83',
  },
];

// Helper to generate a batch of 80+ dynamic attendees so tables, filters, and searches feel huge and alive
export function getFullAttendeeDataset(): Attendee[] {
  const dataset = [...mockAttendees];
  const firstNames = ['Ramesh', 'Vijay', 'Manoj', 'Deepa', 'Sangeetha', 'Vinod', 'Prakash', 'Lavanya', 'Pradeep', 'Saranya', 'Gokul', 'Nithya', 'Ashwin', 'Poornima', 'Mohan', 'Shankar', 'Geetha', 'Subramanian', 'Anitha', 'Kishore'];
  const lastNames = ['Chettiar', 'Thevar', 'Iyer', 'Pillai', 'Mudaliar', 'Gounder', 'Nadar', 'Menon', 'Rao', 'Reddy', 'Chidambaram', 'Sethupathi', 'Alagappan', 'Vasan', 'Sekar', 'Pandian', 'Mani', 'Narayanan', 'Prabhu', 'Rajan'];
  const companies = ['Madurai Castings', 'Kovai Tech Park', 'Chettinad Logistics', 'Vaigai Textiles', 'Pandian Agro', 'South India Software', 'Thillai Spices', 'Salem Steel Works', 'Erode Weaving Mills', 'Nellai IT Labs'];
  const roles = ['Managing Director', 'Technical Lead', 'General Manager', 'Founder', 'Operations Head', 'Senior Consultant', 'Marketing Manager'];
  const cities = ['Madurai', 'Chennai', 'Coimbatore', 'Trichy', 'Salem', 'Bangalore', 'Erode', 'Tirunelveli'];

  for (let i = 21; i <= 105; i++) {
    const fn = firstNames[i % firstNames.length];
    const ln = lastNames[(i * 3) % lastNames.length];
    const comp = companies[i % companies.length];
    const role = roles[i % roles.length];
    const city = cities[i % cities.length];
    const regId = `EVT26-${String(100 + i).padStart(6, '0')}`;
    const isCheckedIn = i % 3 === 0;

    dataset.push({
      id: `att-gen-${i}`,
      registrationId: regId,
      eventId: 'evt-business-summit-2026',
      eventName: 'Business Summit 2026',
      fullName: `${fn} ${ln}`,
      email: `${(fn || 'user').toLowerCase()}.${(ln || 'name').toLowerCase()}@${(comp || 'corp').toLowerCase().replace(/\s+/g, '')}.in`,
      phone: `+91 ${90000 + (i * 123) % 9999} ${10000 + (i * 456) % 89999}`,
      company: comp,
      jobTitle: role,
      city: city,
      ticketType: i % 5 === 0 ? 'VIP Delegate' : (i % 4 === 0 ? 'Startup Founder' : 'General Attendee'),
      status: isCheckedIn ? 'checked_in' : (i % 22 === 0 ? 'cancelled' : 'registered'),
      registeredAt: `2026-09-${String(5 + (i % 9)).padStart(2, '0')}T${String(9 + (i % 8)).padStart(2, '0')}:20:00Z`,
      qrToken: `TOK_EVT26_${String(100 + i).padStart(6, '0')}_HASH`,
      checkedInAt: isCheckedIn ? `2026-09-15T${String(9 + (i % 3)).padStart(2, '0')}:${String((i * 7) % 59).padStart(2, '0')}:15Z` : undefined,
      checkedInBy: isCheckedIn ? (i % 2 === 0 ? 'Rahul Sundar (Staff 01)' : 'Priya Mani (Staff 02)') : undefined,
      checkedInEntrance: isCheckedIn ? (i % 3 === 0 ? 'Entrance A (North Gate / VIP)' : (i % 3 === 1 ? 'Entrance B (Main Hall General)' : 'Entrance C (East Wing & Media)')) : undefined,
    });
  }

  return dataset;
}
