import { EventItem } from '../types';

export const mockEvents: EventItem[] = [
  {
    id: 'evt-business-summit-2026',
    slug: 'business-summit-2026',
    organizationId: 'org_abc_events',
    organizationName: 'ABC Events & Summits',
    name: 'Business Summit 2026',
    description: 'The premier annual congregation of visionary founders, investors, enterprise leaders, and policymakers across South India. Features 20+ keynote speakers, panel discussions, B2B matchmaking, and gala networking.',
    category: 'Conference & Summit',
    date: '2026-09-15',
    startTime: '09:00 AM',
    endTime: '05:30 PM',
    venueName: 'Grand Madurai Convention Centre, Hall A & B',
    venueAddress: '12 Ring Road Bypass, Near Mattuthavani',
    city: 'Madurai',
    organizerName: 'Anand Kumar',
    organizerContact: '+91 98421 88390',
    organizerEmail: 'summit@abcevents.in',
    website: 'https://businesssummit2026.in',
    status: 'published',
    branding: {
      primaryColor: '#4f46e5',
      secondaryColor: '#312e81',
      logoUrl: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=150&auto=format&fit=crop&q=80',
      coverImageUrl: 'https://images.unsplash.com/photo-1511578314322-379afb476865?w=1200&auto=format&fit=crop&q=80',
      theme: 'light',
    },
    fields: [
      { id: 'f_name', label: 'Full Name', type: 'text', required: true, systemField: true, placeholder: 'e.g. Arun Kumar' },
      { id: 'f_email', label: 'Work Email', type: 'email', required: true, systemField: true, placeholder: 'arun@company.com' },
      { id: 'f_phone', label: 'Mobile Number (WhatsApp Enabled)', type: 'phone', required: true, systemField: true, placeholder: '+91 98765 43210' },
      { id: 'f_company', label: 'Company / Organization Name', type: 'text', required: true, placeholder: 'e.g. ABC Technologies Pvt Ltd' },
      { id: 'f_designation', label: 'Job Title / Designation', type: 'text', required: true, placeholder: 'e.g. Founder & Managing Director' },
      { id: 'f_city', label: 'City of Residence', type: 'text', required: true, placeholder: 'e.g. Madurai' },
      { id: 'f_delegatetype', label: 'Delegate Category', type: 'dropdown', required: true, options: ['VIP Delegate', 'General Attendee', 'Startup Founder', 'Investor', 'Media / Press'] },
      { id: 'f_diet', label: 'Dietary Preference', type: 'radio', required: false, options: ['South Indian Vegetarian', 'Non-Vegetarian', 'Jain Meal'] },
    ],
    settings: {
      capacity: 1500,
      registrationOpenDate: '2026-06-01',
      registrationCloseDate: '2026-09-14',
      autoGenerateQRPass: true,
      showPassAfterRegistration: true,
      allowAttendeeEdit: true,
      enableEmailConfirmation: true,
      enableWhatsAppConfirmation: true,
      enableQRCheckIn: true,
      enableManualSearch: true,
      allowStaffCheckIn: true,
      requireEntranceSelection: true,
      entrances: [
        { id: 'ent-a', name: 'Entrance A (North Gate / VIP)', color: '#4f46e5', checkInCount: 312 },
        { id: 'ent-b', name: 'Entrance B (Main Hall General)', color: '#0284c7', checkInCount: 284 },
        { id: 'ent-c', name: 'Entrance C (East Wing & Media)', color: '#059669', checkInCount: 280 },
      ],
      tags: ['Leadership', 'B2B', 'Tech', 'Networking'],
    },
    createdAt: '2026-05-10',
    updatedAt: '2026-08-20',
    stats: {
      totalRegistrations: 1248,
      totalCheckedIn: 876,
      totalCancelled: 24,
      totalWalkIns: 18,
      capacity: 1500,
      attendancePercentage: 70.2,
    },
  },
  {
    id: 'evt-tamil-entrepreneurs-meet',
    slug: 'tamil-entrepreneurs-meet-2026',
    organizationId: 'org_tamil_entrepreneurs',
    organizationName: 'Tamil Entrepreneurs Forum',
    name: 'Tamil Entrepreneurs Meet 2026',
    description: 'A mega networking symposium bringing over 2,000 NextGen entrepreneurs, MSME owners, and global diaspora investors together to accelerate cross-border trade, manufacturing, and tech innovation.',
    category: 'Networking Meetup',
    date: '2026-09-28',
    startTime: '10:00 AM',
    endTime: '06:00 PM',
    venueName: 'Chennai Trade Centre, Nandambakkam',
    venueAddress: 'Mount Poonamallee High Road',
    city: 'Chennai',
    organizerName: 'Priya Rajendran',
    organizerContact: '+91 97890 12345',
    organizerEmail: 'meet@tamilforum.org',
    website: 'https://tamilentrepreneurs.org/meet2026',
    status: 'registration_open',
    branding: {
      primaryColor: '#0284c7',
      secondaryColor: '#0369a1',
      coverImageUrl: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=1200&auto=format&fit=crop&q=80',
      theme: 'light',
    },
    fields: [
      { id: 'f_name', label: 'Full Name', type: 'text', required: true, systemField: true },
      { id: 'f_email', label: 'Email Address', type: 'email', required: true, systemField: true },
      { id: 'f_phone', label: 'Mobile Number', type: 'phone', required: true, systemField: true },
      { id: 'f_company', label: 'Business / Venture Name', type: 'text', required: true },
      { id: 'f_sector', label: 'Industry Sector', type: 'dropdown', required: true, options: ['Manufacturing & Textiles', 'IT & SaaS', 'Agri & Food Processing', 'Healthcare', 'Logistics'] },
    ],
    settings: {
      capacity: 2000,
      registrationOpenDate: '2026-07-01',
      registrationCloseDate: '2026-09-27',
      autoGenerateQRPass: true,
      showPassAfterRegistration: true,
      allowAttendeeEdit: true,
      enableEmailConfirmation: true,
      enableWhatsAppConfirmation: true,
      enableQRCheckIn: true,
      enableManualSearch: true,
      allowStaffCheckIn: true,
      requireEntranceSelection: true,
      entrances: [
        { id: 'ent-1', name: 'Main Pavilion Hall 1', color: '#0284c7', checkInCount: 0 },
        { id: 'ent-2', name: 'West Gate Entrance', color: '#059669', checkInCount: 0 },
      ],
      tags: ['Entrepreneurs', 'MSME', 'Investments'],
    },
    createdAt: '2026-06-15',
    updatedAt: '2026-08-25',
    stats: {
      totalRegistrations: 1840,
      totalCheckedIn: 0,
      totalCancelled: 12,
      totalWalkIns: 0,
      capacity: 2000,
      attendancePercentage: 0,
    },
  },
  {
    id: 'evt-digital-marketing-conf',
    slug: 'digital-marketing-conference-2026',
    organizationId: 'org_abc_events',
    organizationName: 'ABC Events & Summits',
    name: 'Digital Marketing & Growth Conference',
    description: 'Master AI-driven performance marketing, retention loops, SEO strategies, and creator economy branding with India’s top CMOs and growth hackers.',
    category: 'Conference',
    date: '2026-10-10',
    startTime: '09:30 AM',
    endTime: '04:30 PM',
    venueName: 'Le Meridien Convention Centre',
    venueAddress: 'Avinashi Road',
    city: 'Coimbatore',
    organizerName: 'Anand Kumar',
    organizerContact: '+91 98421 88390',
    organizerEmail: 'growth@abcevents.in',
    status: 'registration_open',
    branding: {
      primaryColor: '#7c3aed',
      secondaryColor: '#5b21b6',
      coverImageUrl: 'https://images.unsplash.com/photo-1505373877841-8d25f7d46678?w=1200&auto=format&fit=crop&q=80',
      theme: 'light',
    },
    fields: [
      { id: 'f_name', label: 'Full Name', type: 'text', required: true, systemField: true },
      { id: 'f_email', label: 'Email', type: 'email', required: true, systemField: true },
      { id: 'f_phone', label: 'Phone', type: 'phone', required: true, systemField: true },
      { id: 'f_experience', label: 'Marketing Experience', type: 'dropdown', required: false, options: ['0-2 years', '3-5 years', '6+ years', 'Agency Owner'] },
    ],
    settings: {
      capacity: 800,
      registrationOpenDate: '2026-08-01',
      registrationCloseDate: '2026-10-09',
      autoGenerateQRPass: true,
      showPassAfterRegistration: true,
      allowAttendeeEdit: true,
      enableEmailConfirmation: true,
      enableWhatsAppConfirmation: true,
      enableQRCheckIn: true,
      enableManualSearch: true,
      allowStaffCheckIn: true,
      requireEntranceSelection: false,
      entrances: [
        { id: 'ent-main', name: 'Main Lobby Registration', color: '#7c3aed', checkInCount: 0 },
      ],
      tags: ['Growth', 'Marketing', 'AI'],
    },
    createdAt: '2026-07-20',
    updatedAt: '2026-08-22',
    stats: {
      totalRegistrations: 642,
      totalCheckedIn: 0,
      totalCancelled: 5,
      totalWalkIns: 0,
      capacity: 800,
      attendancePercentage: 0,
    },
  },
  {
    id: 'evt-startup-growth-workshop',
    slug: 'startup-growth-workshop',
    organizationId: 'org_abc_events',
    organizationName: 'ABC Events & Summits',
    name: 'Startup Growth & Pitch Intensive Workshop',
    description: 'Hands-on bootcamp for early-stage founders: unit economics, VC pitch deck clinic, and seed funding roadmap with angel syndicates.',
    category: 'Workshop',
    date: '2026-08-20',
    startTime: '10:00 AM',
    endTime: '04:00 PM',
    venueName: 'Kallazhagar Incubation Hub',
    venueAddress: 'Alagar Kovil Main Road',
    city: 'Madurai',
    organizerName: 'Anand Kumar',
    organizerContact: '+91 98421 88390',
    organizerEmail: 'bootcamp@abcevents.in',
    status: 'completed',
    branding: {
      primaryColor: '#059669',
      secondaryColor: '#065f46',
      coverImageUrl: 'https://images.unsplash.com/photo-1528605248644-14dd04022da1?w=1200&auto=format&fit=crop&q=80',
      theme: 'light',
    },
    fields: [
      { id: 'f_name', label: 'Full Name', type: 'text', required: true, systemField: true },
      { id: 'f_email', label: 'Email', type: 'email', required: true, systemField: true },
      { id: 'f_phone', label: 'Phone', type: 'phone', required: true, systemField: true },
      { id: 'f_stage', label: 'Startup Stage', type: 'dropdown', required: true, options: ['Ideation', 'MVP Built', 'Early Revenue', 'Seed Funded'] },
    ],
    settings: {
      capacity: 250,
      registrationOpenDate: '2026-07-01',
      registrationCloseDate: '2026-08-19',
      autoGenerateQRPass: true,
      showPassAfterRegistration: true,
      allowAttendeeEdit: false,
      enableEmailConfirmation: true,
      enableWhatsAppConfirmation: true,
      enableQRCheckIn: true,
      enableManualSearch: true,
      allowStaffCheckIn: true,
      requireEntranceSelection: false,
      entrances: [{ id: 'ent-hub', name: 'Incubation Main Entrance', color: '#059669', checkInCount: 228 }],
      tags: ['Startups', 'Venture Capital', 'Workshop'],
    },
    createdAt: '2026-06-01',
    updatedAt: '2026-08-21',
    stats: {
      totalRegistrations: 245,
      totalCheckedIn: 228,
      totalCancelled: 12,
      totalWalkIns: 5,
      capacity: 250,
      attendancePercentage: 93.0,
    },
  },
  {
    id: 'evt-annual-dealer-conference',
    slug: 'annual-dealer-conference-2026',
    organizationId: 'org_coimbatore_expo',
    organizationName: 'Coimbatore Expo & Tech Conclaves',
    name: 'Annual National Dealer & Distributor Conclave',
    description: 'Exclusive national distributors conclave showcasing 2026-27 product lines, dealer excellence awards, and supply chain tech sessions.',
    category: 'Corporate Conclave',
    date: '2026-11-05',
    startTime: '09:00 AM',
    endTime: '07:00 PM',
    venueName: 'The Residency Towers Grand Ballroom',
    venueAddress: 'Race Course Road',
    city: 'Coimbatore',
    organizerName: 'Karthik Sundaram',
    organizerContact: '+91 94432 55670',
    organizerEmail: 'dealer2026@cbtexpo.com',
    status: 'draft',
    branding: {
      primaryColor: '#d97706',
      secondaryColor: '#b45309',
      coverImageUrl: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=1200&auto=format&fit=crop&q=80',
      theme: 'light',
    },
    fields: [
      { id: 'f_name', label: 'Full Name', type: 'text', required: true, systemField: true },
      { id: 'f_email', label: 'Email', type: 'email', required: true, systemField: true },
      { id: 'f_phone', label: 'Phone', type: 'phone', required: true, systemField: true },
      { id: 'f_dealership', label: 'Dealership / Agency Name', type: 'text', required: true },
    ],
    settings: {
      capacity: 500,
      registrationOpenDate: '2026-09-01',
      registrationCloseDate: '2026-11-04',
      autoGenerateQRPass: true,
      showPassAfterRegistration: true,
      allowAttendeeEdit: true,
      enableEmailConfirmation: true,
      enableWhatsAppConfirmation: true,
      enableQRCheckIn: true,
      enableManualSearch: true,
      allowStaffCheckIn: true,
      requireEntranceSelection: true,
      entrances: [{ id: 'ent-a', name: 'Main Ballroom Gate', color: '#d97706', checkInCount: 0 }],
      tags: ['Dealer', 'B2B', 'Awards'],
    },
    createdAt: '2026-08-01',
    updatedAt: '2026-08-15',
    stats: {
      totalRegistrations: 0,
      totalCheckedIn: 0,
      totalCancelled: 0,
      totalWalkIns: 0,
      capacity: 500,
      attendancePercentage: 0,
    },
  },
  {
    id: 'evt-tech-leaders-forum',
    slug: 'tech-leaders-forum-bangalore',
    organizationId: 'org_apex_conferences',
    organizationName: 'Apex Leaders Network',
    name: 'Tech Leaders Forum: AI in Enterprise',
    description: 'High-density technical conference focused on Generative AI architectures, cloud resilience, and CTO best practices.',
    category: 'Technology',
    date: '2026-10-24',
    startTime: '08:30 AM',
    endTime: '06:00 PM',
    venueName: 'Sheraton Grand Bangalore Hotel at Brigade Gateway',
    venueAddress: 'Rajajinagar-Malleshwaram',
    city: 'Bangalore',
    organizerName: 'Dr. R. Meenakshi',
    organizerContact: '+91 98840 99881',
    organizerEmail: 'techforum@apexnet.in',
    status: 'published',
    branding: {
      primaryColor: '#6366f1',
      secondaryColor: '#4338ca',
      coverImageUrl: 'https://images.unsplash.com/photo-1511578314322-379afb476865?w=1200&auto=format&fit=crop&q=80',
      theme: 'light',
    },
    fields: [
      { id: 'f_name', label: 'Full Name', type: 'text', required: true, systemField: true },
      { id: 'f_email', label: 'Work Email', type: 'email', required: true, systemField: true },
      { id: 'f_phone', label: 'Phone Number', type: 'phone', required: true, systemField: true },
      { id: 'f_company', label: 'Organization', type: 'text', required: true },
      { id: 'f_tech', label: 'Primary Tech Stack', type: 'dropdown', required: false, options: ['Cloud & Distributed Systems', 'AI / ML / Data', 'Cybersecurity', 'Fintech Architecture'] },
    ],
    settings: {
      capacity: 1200,
      registrationOpenDate: '2026-08-10',
      registrationCloseDate: '2026-10-23',
      autoGenerateQRPass: true,
      showPassAfterRegistration: true,
      allowAttendeeEdit: true,
      enableEmailConfirmation: true,
      enableWhatsAppConfirmation: true,
      enableQRCheckIn: true,
      enableManualSearch: true,
      allowStaffCheckIn: true,
      requireEntranceSelection: true,
      entrances: [
        { id: 'ent-lead-1', name: 'Grand Ballroom Entrance', color: '#6366f1', checkInCount: 0 },
        { id: 'ent-lead-2', name: 'VIP & Speaker Fast Track', color: '#8b5cf6', checkInCount: 0 },
      ],
      tags: ['Engineering', 'AI', 'Cloud', 'CTO'],
    },
    createdAt: '2026-07-15',
    updatedAt: '2026-08-20',
    stats: {
      totalRegistrations: 980,
      totalCheckedIn: 0,
      totalCancelled: 14,
      totalWalkIns: 0,
      capacity: 1200,
      attendancePercentage: 0,
    },
  },
  {
    id: 'evt-madurai-industrial-expo',
    slug: 'madurai-industrial-trade-expo-2026',
    organizationId: 'org_abc_events',
    organizationName: 'ABC Events & Summits',
    name: 'Madurai Industrial & MSME Trade Expo',
    description: '3-day massive exhibition featuring machinery, packaging equipment, renewable energy, and agro-tech innovations from over 300 manufacturing brands.',
    category: 'Exhibition & Trade Fair',
    date: '2026-10-18',
    startTime: '10:00 AM',
    endTime: '06:30 PM',
    venueName: 'IDA Scudder Trade Grounds',
    venueAddress: 'Alagar Kovil Road',
    city: 'Madurai',
    organizerName: 'Anand Kumar',
    organizerContact: '+91 98421 88390',
    organizerEmail: 'expo@abcevents.in',
    status: 'published',
    branding: {
      primaryColor: '#0284c7',
      secondaryColor: '#075985',
      coverImageUrl: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=1200&auto=format&fit=crop&q=80',
      theme: 'light',
    },
    fields: [
      { id: 'f_name', label: 'Visitor / Delegate Name', type: 'text', required: true, systemField: true },
      { id: 'f_email', label: 'Email', type: 'email', required: true, systemField: true },
      { id: 'f_phone', label: 'Mobile Number', type: 'phone', required: true, systemField: true },
      { id: 'f_business', label: 'Business Name & GST No', type: 'text', required: false },
    ],
    settings: {
      capacity: 5000,
      registrationOpenDate: '2026-07-15',
      registrationCloseDate: '2026-10-17',
      autoGenerateQRPass: true,
      showPassAfterRegistration: true,
      allowAttendeeEdit: true,
      enableEmailConfirmation: true,
      enableWhatsAppConfirmation: true,
      enableQRCheckIn: true,
      enableManualSearch: true,
      allowStaffCheckIn: true,
      requireEntranceSelection: true,
      entrances: [
        { id: 'ent-gate-1', name: 'Gate 1 (Machinery Expo)', color: '#0284c7', checkInCount: 0 },
        { id: 'ent-gate-2', name: 'Gate 2 (General Public & Buyers)', color: '#059669', checkInCount: 0 },
      ],
      tags: ['Manufacturing', 'MSME', 'Trade Fair'],
    },
    createdAt: '2026-07-01',
    updatedAt: '2026-08-24',
    stats: {
      totalRegistrations: 2430,
      totalCheckedIn: 0,
      totalCancelled: 18,
      totalWalkIns: 0,
      capacity: 5000,
      attendancePercentage: 0,
    },
  },
  {
    id: 'evt-healthcare-innovation-summit',
    slug: 'healthcare-innovation-summit-2026',
    organizationId: 'org_apex_conferences',
    organizationName: 'Apex Leaders Network',
    name: 'Healthcare & MedTech Innovation Summit',
    description: 'Transforming clinical outcomes with AI diagnostics, telemedicine, and healthcare robotics.',
    category: 'Healthcare',
    date: '2026-11-12',
    startTime: '09:00 AM',
    endTime: '05:00 PM',
    venueName: 'ITC Grand Chola',
    venueAddress: 'Guindy',
    city: 'Chennai',
    organizerName: 'Dr. R. Meenakshi',
    organizerContact: '+91 98840 99881',
    organizerEmail: 'health@apexnet.in',
    status: 'draft',
    branding: {
      primaryColor: '#0d9488',
      secondaryColor: '#115e59',
      coverImageUrl: 'https://images.unsplash.com/photo-1505373877841-8d25f7d46678?w=1200&auto=format&fit=crop&q=80',
      theme: 'light',
    },
    fields: [
      { id: 'f_name', label: 'Full Name', type: 'text', required: true, systemField: true },
      { id: 'f_email', label: 'Email', type: 'email', required: true, systemField: true },
      { id: 'f_phone', label: 'Phone', type: 'phone', required: true, systemField: true },
      { id: 'f_hospital', label: 'Hospital / Institution', type: 'text', required: true },
    ],
    settings: {
      capacity: 600,
      registrationOpenDate: '2026-09-01',
      registrationCloseDate: '2026-11-11',
      autoGenerateQRPass: true,
      showPassAfterRegistration: true,
      allowAttendeeEdit: true,
      enableEmailConfirmation: true,
      enableWhatsAppConfirmation: true,
      enableQRCheckIn: true,
      enableManualSearch: true,
      allowStaffCheckIn: true,
      requireEntranceSelection: false,
      entrances: [{ id: 'ent-main', name: 'Convention Foyer', color: '#0d9488', checkInCount: 0 }],
      tags: ['Healthcare', 'MedTech', 'Doctors'],
    },
    createdAt: '2026-08-10',
    updatedAt: '2026-08-20',
    stats: {
      totalRegistrations: 0,
      totalCheckedIn: 0,
      totalCancelled: 0,
      totalWalkIns: 0,
      capacity: 600,
      attendancePercentage: 0,
    },
  },
];
