import { Organization, PricingPlan } from '../types';

export const mockOrganizations: Organization[] = [
  {
    id: 'org_abc_events',
    name: 'ABC Events & Summits',
    slug: 'abc-events',
    logoUrl: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=150&auto=format&fit=crop&q=80',
    plan: 'growth',
    ownerName: 'Anand Kumar',
    ownerEmail: 'anand@abcevents.in',
    phone: '+91 98421 88390',
    website: 'https://abcevents.in',
    city: 'Madurai',
    timezone: 'Asia/Kolkata (IST)',
    currency: 'INR (₹)',
    defaultBrandColor: '#4f46e5',
    activeEventsCount: 12,
    totalRegistrationsCount: 8426,
    status: 'active',
    createdAt: '2025-04-12',
  },
  {
    id: 'org_tamil_entrepreneurs',
    name: 'Tamil Entrepreneurs Forum',
    slug: 'tamil-entrepreneurs',
    logoUrl: 'https://images.unsplash.com/photo-1511578314322-379afb476865?w=150&auto=format&fit=crop&q=80',
    plan: 'business',
    ownerName: 'Priya Rajendran',
    ownerEmail: 'priya@tamilforum.org',
    phone: '+91 97890 12345',
    website: 'https://tamilentrepreneurs.org',
    city: 'Chennai',
    timezone: 'Asia/Kolkata (IST)',
    currency: 'INR (₹)',
    defaultBrandColor: '#0284c7',
    activeEventsCount: 8,
    totalRegistrationsCount: 14200,
    status: 'active',
    createdAt: '2025-01-18',
  },
  {
    id: 'org_coimbatore_expo',
    name: 'Coimbatore Expo & Tech Conclaves',
    slug: 'coimbatore-expo',
    logoUrl: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=150&auto=format&fit=crop&q=80',
    plan: 'starter',
    ownerName: 'Karthik Sundaram',
    ownerEmail: 'karthik@cbtexpo.com',
    phone: '+91 94432 55670',
    website: 'https://cbtexpo.com',
    city: 'Coimbatore',
    timezone: 'Asia/Kolkata (IST)',
    currency: 'INR (₹)',
    defaultBrandColor: '#059669',
    activeEventsCount: 4,
    totalRegistrationsCount: 3180,
    status: 'active',
    createdAt: '2025-08-01',
  },
  {
    id: 'org_apex_conferences',
    name: 'Apex Leaders Network',
    slug: 'apex-leaders',
    logoUrl: 'https://images.unsplash.com/photo-1505373877841-8d25f7d46678?w=150&auto=format&fit=crop&q=80',
    plan: 'business',
    ownerName: 'Dr. R. Meenakshi',
    ownerEmail: 'meenakshi@apexnet.in',
    phone: '+91 98840 99881',
    website: 'https://apexleaders.in',
    city: 'Bangalore',
    timezone: 'Asia/Kolkata (IST)',
    currency: 'INR (₹)',
    defaultBrandColor: '#7c3aed',
    activeEventsCount: 15,
    totalRegistrationsCount: 22400,
    status: 'active',
    createdAt: '2024-11-05',
  },
  {
    id: 'org_erode_trade',
    name: 'Erode & Salem Industrial Chamber',
    slug: 'erode-industrial-chamber',
    logoUrl: 'https://images.unsplash.com/photo-1528605248644-14dd04022da1?w=150&auto=format&fit=crop&q=80',
    plan: 'free',
    ownerName: 'Murugan Ganesan',
    ownerEmail: 'murugan@erodetric.org',
    phone: '+91 94860 44211',
    website: 'https://erodetric.org',
    city: 'Erode',
    timezone: 'Asia/Kolkata (IST)',
    currency: 'INR (₹)',
    defaultBrandColor: '#d97706',
    activeEventsCount: 1,
    totalRegistrationsCount: 420,
    status: 'active',
    createdAt: '2026-02-10',
  },
];

export const mockPricingPlans: PricingPlan[] = [
  {
    id: 'free',
    name: 'Free Starter',
    tagline: 'Ideal for single community meetups and testing the platform.',
    monthlyPrice: 0,
    annualPrice: 0,
    eventsAllowed: 1,
    registrationLimit: 100,
    staffSeats: 2,
    whatsappMessages: 0,
    customBranding: false,
    advancedReports: false,
    apiAccess: false,
  },
  {
    id: 'starter',
    name: 'Starter',
    tagline: 'For growing organizers running regular workshops and meetups.',
    monthlyPrice: 999,
    annualPrice: 9990,
    eventsAllowed: 5,
    registrationLimit: 1500,
    staffSeats: 5,
    whatsappMessages: 500,
    customBranding: true,
    advancedReports: false,
    apiAccess: false,
  },
  {
    id: 'growth',
    name: 'Growth',
    tagline: 'For professional conferences, business summits, and large expos.',
    monthlyPrice: 2499,
    annualPrice: 24990,
    eventsAllowed: 20,
    registrationLimit: 10000,
    staffSeats: 25,
    whatsappMessages: 5000,
    customBranding: true,
    advancedReports: true,
    apiAccess: true,
    popular: true,
  },
  {
    id: 'business',
    name: 'Enterprise / Business',
    tagline: 'Full white-labeling, unlimited events, dedicated support & SLA.',
    monthlyPrice: 6999,
    annualPrice: 69990,
    eventsAllowed: 'Unlimited',
    registrationLimit: 'Unlimited',
    staffSeats: 'Unlimited',
    whatsappMessages: 25000,
    customBranding: true,
    advancedReports: true,
    apiAccess: true,
  },
];
