import { StaffMember, CheckInLog, MessageCampaign } from '../types';

export const mockStaff: StaffMember[] = [
  {
    id: 'staff-01',
    organizationId: 'org_abc_events',
    eventId: 'evt-business-summit-2026',
    name: 'Rahul Sundar',
    email: 'rahul.s@abcevents.in',
    phone: '+91 98421 77112',
    role: 'check_in_staff',
    assignedEntrance: 'Entrance A (North Gate / VIP)',
    status: 'active',
    lastActive: 'Just now',
    checkInCount: 312,
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'staff-02',
    organizationId: 'org_abc_events',
    eventId: 'evt-business-summit-2026',
    name: 'Priya Mani',
    email: 'priya.m@abcevents.in',
    phone: '+91 97890 88231',
    role: 'check_in_staff',
    assignedEntrance: 'Entrance B (Main Hall General)',
    status: 'active',
    lastActive: '1 min ago',
    checkInCount: 284,
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'staff-03',
    organizationId: 'org_abc_events',
    eventId: 'evt-business-summit-2026',
    name: 'Karthik Raja',
    email: 'karthik.r@abcevents.in',
    phone: '+91 94432 11990',
    role: 'check_in_staff',
    assignedEntrance: 'Entrance C (East Wing & Media)',
    status: 'active',
    lastActive: '3 mins ago',
    checkInCount: 280,
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'staff-04',
    organizationId: 'org_abc_events',
    eventId: 'evt-business-summit-2026',
    name: 'Gowri Shankar',
    email: 'gowri@abcevents.in',
    phone: '+91 99401 55443',
    role: 'event_manager',
    assignedEntrance: 'All Entrances (Floor Lead)',
    status: 'active',
    lastActive: 'Just now',
    checkInCount: 0,
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'staff-05',
    organizationId: 'org_abc_events',
    eventId: 'evt-business-summit-2026',
    name: 'Archana V.',
    email: 'archana@abcevents.in',
    phone: '+91 98841 22339',
    role: 'viewer',
    assignedEntrance: 'Helpdesk & VIP Lounge',
    status: 'inactive',
    lastActive: '2 hours ago',
    checkInCount: 0,
  },
];

export const mockCheckInLogs: CheckInLog[] = [
  {
    id: 'chk-001',
    eventId: 'evt-business-summit-2026',
    attendeeId: 'att-001',
    attendeeName: 'Arun Kumar',
    registrationId: 'EVT26-000123',
    company: 'ABC Technologies Pvt Ltd',
    timestamp: '10:41:32 AM',
    fullDateTime: '2026-09-15T10:41:32Z',
    entrance: 'Entrance A (North Gate / VIP)',
    staffName: 'Rahul Sundar (Staff 01)',
    staffId: 'staff-01',
    device: 'iPad Pro Gate A',
    type: 'qr_scan',
  },
  {
    id: 'chk-002',
    eventId: 'evt-business-summit-2026',
    attendeeId: 'att-002',
    attendeeName: 'Priya Raj',
    registrationId: 'EVT26-000124',
    company: 'Chennai Angel Ventures',
    timestamp: '10:41:21 AM',
    fullDateTime: '2026-09-15T10:41:21Z',
    entrance: 'Entrance B (Main Hall General)',
    staffName: 'Priya Mani (Staff 02)',
    staffId: 'staff-02',
    device: 'Galaxy Tab Gate B',
    type: 'qr_scan',
  },
  {
    id: 'chk-003',
    eventId: 'evt-business-summit-2026',
    attendeeId: 'att-003',
    attendeeName: 'Karthik Subramanian',
    registrationId: 'EVT26-000125',
    company: 'Madurai Finserve Logistics',
    timestamp: '10:40:58 AM',
    fullDateTime: '2026-09-15T10:40:58Z',
    entrance: 'Entrance A (North Gate / VIP)',
    staffName: 'Rahul Sundar (Staff 01)',
    staffId: 'staff-01',
    device: 'iPad Pro Gate A',
    type: 'qr_scan',
  },
  {
    id: 'chk-004',
    eventId: 'evt-business-summit-2026',
    attendeeId: 'att-004',
    attendeeName: 'Divya Natarajan',
    registrationId: 'EVT26-000126',
    company: 'SaaSMetric Global',
    timestamp: '10:39:14 AM',
    fullDateTime: '2026-09-15T10:39:14Z',
    entrance: 'Entrance C (East Wing & Media)',
    staffName: 'Karthik Raja (Staff 03)',
    staffId: 'staff-03',
    device: 'Pixel 8 Pro Gate C',
    type: 'qr_scan',
  },
  {
    id: 'chk-005',
    eventId: 'evt-business-summit-2026',
    attendeeId: 'att-008',
    attendeeName: 'Meera Krishnan',
    registrationId: 'EVT26-000130',
    company: 'The Hindu Businessline',
    timestamp: '10:35:10 AM',
    fullDateTime: '2026-09-15T10:35:10Z',
    entrance: 'Entrance C (East Wing & Media)',
    staffName: 'Karthik Raja (Staff 03)',
    staffId: 'staff-03',
    device: 'Pixel 8 Pro Gate C',
    type: 'qr_scan',
  },
  {
    id: 'chk-006',
    eventId: 'evt-business-summit-2026',
    attendeeId: 'att-010',
    attendeeName: 'Lakshmi Narayanan',
    registrationId: 'EVT26-000132',
    company: 'Pandian Packaging Ltd',
    timestamp: '09:45:30 AM',
    fullDateTime: '2026-09-15T09:45:30Z',
    entrance: 'Entrance A (North Gate / VIP)',
    staffName: 'Rahul Sundar (Staff 01)',
    staffId: 'staff-01',
    device: 'iPad Pro Gate A',
    type: 'walk_in',
  },
];

export const mockCampaigns: MessageCampaign[] = [
  {
    id: 'cmp-001',
    eventId: 'evt-business-summit-2026',
    title: 'Registration Confirmation & Digital QR Pass',
    type: 'qr_pass_delivery',
    channel: 'both',
    audience: 'all_registered',
    status: 'sent',
    sentAt: '2026-09-14T09:00:00Z',
    recipientCount: 1248,
    deliveryRate: 99.4,
    templatePreview: 'Hello {{name}}, your digital pass for Business Summit 2026 is confirmed! Tap here to download your QR badge: {{pass_url}}',
  },
  {
    id: 'cmp-002',
    eventId: 'evt-business-summit-2026',
    title: 'Event-Day Entrance & Parking Guidelines',
    type: 'event_day_alert',
    channel: 'whatsapp',
    audience: 'all_registered',
    status: 'sent',
    sentAt: '2026-09-15T07:30:00Z',
    recipientCount: 1248,
    deliveryRate: 98.8,
    templatePreview: 'Good morning {{name}}! Gates open at 8:30 AM. Present your QR code at {{entrance_assigned}} for seamless check-in.',
  },
  {
    id: 'cmp-003',
    eventId: 'evt-business-summit-2026',
    title: 'Post-Event Keynote Slides & Thank You Note',
    type: 'thank_you',
    channel: 'email',
    audience: 'checked_in_only',
    status: 'ready',
    recipientCount: 876,
    deliveryRate: 0,
    templatePreview: 'Thank you for attending Business Summit 2026! Access speaker presentations, photo gallery, and delegate directory here.',
  },
];
